[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

[fuzz]
    failure_persist_file="/tests/failures.txt"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fail_on_revert=true
optimizer = true
optimizer_runs = 200
via_ir = true

gas_reports=["CustomBuilderGovernor", "GovernmentToken", "DeployContract"]

[rpc_endpoints]
ETH_ALCHEMY_SEPOLIA_RPC_URL="https://eth-sepolia.g.alchemy.com/v2/7_aeucI8FLv0cq9-vXWPCLfVbqxWjHP_"